using System;
using Soenneker.Extensions.Enumerable.String;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Soenneker.Quark.Gen.Validation.BuildTasks;

internal static class ValidationEmitter
{
    private const string Annotations = "System.ComponentModel.DataAnnotations.";

    internal static string Emit(CSharpCompilation compilation, CancellationToken cancellationToken = default)
    {
        var output = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        var seen = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
        foreach (var tree in compilation.SyntaxTrees.OrderBy(t => t.FilePath, StringComparer.Ordinal))
        {
            cancellationToken.ThrowIfCancellationRequested();
            var semantic = compilation.GetSemanticModel(tree);
            foreach (var declaration in tree.GetRoot().DescendantNodes().OfType<TypeDeclarationSyntax>())
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (semantic.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type || !seen.Add(type)) continue;
                var properties = Properties(type).ToArray();
                if (!type.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "Soenneker.Quark.GenerateQuarkValidationAttribute") &&
                    !properties.Any(p => Attributes(p).Any(IsValidation))) continue;
                if (type.IsStatic || type.IsRefLikeType || type.IsFileLocal || type.TypeKind is not (TypeKind.Class or TypeKind.Struct))
                    throw Error(type, "Validation models must be ordinary classes, records, or structs.");
                var chain = new Stack<INamedTypeSymbol>();
                for (var current = type; current is not null; current = current.ContainingType)
                {
                    if (current.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is not TypeDeclarationSyntax d || !d.Modifiers.Any(SyntaxKind.PartialKeyword)))
                        throw Error(current, "Add the partial modifier to this model and its containing types so generated code can access nested and generic models.");
                    chain.Push(current);
                }
                if (!type.ContainingNamespace.IsGlobalNamespace) output.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine(" {");
                foreach (var current in chain)
                {
                    output.Append("partial ").Append(current.IsRecord ? current.TypeKind == TypeKind.Struct ? "record struct " : "record class " : current.TypeKind == TypeKind.Struct ? "struct " : "class ")
                        .Append('@').Append(current.Name);
                    if (current.TypeParameters.Length > 0) output.Append('<').Append(current.TypeParameters.Select(p => "@" + p.Name).ToCommaSeparatedString(includeSpace: true)).Append('>');
                    if (SymbolEqualityComparer.Default.Equals(current, type)) output.Append(" : global::Soenneker.Quark.IGeneratedQuarkValidation");
                    output.AppendLine(" {");
                }
                output.AppendLine("void global::Soenneker.Quark.IGeneratedQuarkValidation.ValidateField(string memberName, global::System.Collections.Generic.ICollection<global::System.ComponentModel.DataAnnotations.ValidationResult> results) {");
                output.AppendLine("switch (memberName) {");
                foreach (var property in properties) EmitProperty(output, type, property, properties);
                output.AppendLine("default: throw new global::System.ArgumentException(\"Unknown public validation property: \" + memberName, nameof(memberName));\n}\n}");
                foreach (var _ in chain) output.AppendLine("}");
                if (!type.ContainingNamespace.IsGlobalNamespace) output.AppendLine("}");
            }
        }
        if (output.ToString().Contains("new global::Soenneker.Quark.Generated.TypedRangeAttribute<")) output.AppendLine(TypedRangeSource.Text);
        if (output.ToString().Contains("new global::Soenneker.Quark.Generated.ComparisonMessageAttribute(")) output.AppendLine(ComparisonSource.Text);
        return output.ToString();
    }

    private static IEnumerable<IPropertySymbol> Properties(INamedTypeSymbol type)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);
        for (var current = type; current is not null; current = current.BaseType)
            foreach (var property in current.GetMembers().OfType<IPropertySymbol>())
                if (names.Add(property.Name) && !property.IsStatic && !property.IsIndexer && property.DeclaredAccessibility == Accessibility.Public &&
                    property.GetMethod?.DeclaredAccessibility == Accessibility.Public)
                    yield return property;
    }

    private static IEnumerable<AttributeData> Attributes(IPropertySymbol property)
    {
        var attributes = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
        var inherited = false;
        for (var current = property; current is not null; current = current.OverriddenProperty)
        {
            foreach (var attribute in current.GetAttributes())
            {
                if (attribute.AttributeClass is null) continue;
                var usage = attribute.AttributeClass.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "System.AttributeUsageAttribute");
                if (inherited && usage?.NamedArguments.Any(a => a.Key == "Inherited" && a.Value.Value is false) == true) continue;
                var multiple = usage?.NamedArguments.Any(a => a.Key == "AllowMultiple" && a.Value.Value is true) == true;
                if (attributes.Add(attribute.AttributeClass) || multiple) yield return attribute;
            }
            inherited = true;
        }
    }

    private static bool IsValidation(AttributeData attribute)
    {
        if (attribute.AttributeClass?.ToDisplayString() is "Soenneker.Quark.QuarkCompareAttribute" or "Soenneker.Quark.QuarkRangeAttribute") return true;
        for (var current = attribute.AttributeClass; current is not null; current = current.BaseType)
            if (current.ToDisplayString() == Annotations + "ValidationAttribute") return true;
        return false;
    }

    private static bool IsRequired(AttributeData attribute)
    {
        for (var current = attribute.AttributeClass; current is not null; current = current.BaseType)
            if (current.ToDisplayString() == Annotations + "RequiredAttribute") return true;
        return false;
    }

    private static void EmitProperty(StringBuilder output, INamedTypeSymbol model, IPropertySymbol property, IPropertySymbol[] properties)
    {
        var attributes = Attributes(property).Where(IsValidation).OrderBy(a => IsRequired(a) ? 0 : 1).ToArray();
        output.Append("case ").Append(Literal(property.Name)).AppendLine(": {");
        // Match TryValidateProperty: even a field without annotations reads its current getter.
        output.Append("var value = this.@").Append(property.Name).AppendLine(";");
        if (attributes.Length != 0)
        {
            output.Append("var displayName = ").Append(Display(property)).Append(" ?? ").Append(Literal(property.Name)).AppendLine(";");
            output.Append("var context = new global::System.ComponentModel.DataAnnotations.ValidationContext(this, global::System.String.IsNullOrEmpty(displayName) ? ((object)this).GetType().Name : displayName")
                .Append(", null, null) { MemberName = ").Append(Literal(property.Name)).AppendLine(" };");
            for (var i = 0; i < attributes.Length; i++)
            {
                var attribute = attributes[i];
                var name = attribute.AttributeClass!.ToDisplayString();
                var variable = "attribute" + i;
                var result = "result" + i;
                if (name == Annotations + "CompareAttribute" || name == "Soenneker.Quark.QuarkCompareAttribute")
                {
                    var otherName = attribute.ConstructorArguments[0].Value as string;
                    var other = properties.FirstOrDefault(p => p.Name == otherName);
                    if (other is null) throw Error(property, "Compare references an unknown public readable property: " + otherName);
                    output.Append("var ").Append(variable).Append(" = ").Append(Construct(attribute, property, Display(other))).AppendLine(";");
                    output.Append("if (!global::System.Object.Equals(value, this.@").Append(other.Name).AppendLine("))");
                    output.Append("results.Add(new global::System.ComponentModel.DataAnnotations.ValidationResult(").Append(variable).Append(".FormatErrorMessage(context.DisplayName), new[] { memberName }));").AppendLine();
                    continue;
                }
                output.Append("var ").Append(variable).Append(" = ").Append(Construct(attribute, property)).AppendLine(";");
                output.Append("var ").Append(result).Append(" = ").Append(variable).AppendLine(".GetValidationResult(value, context);");
                output.Append("if (").Append(result).Append(" is not null) { results.Add(").Append(result).Append(");")
                    .Append(IsRequired(attribute) ? " return;" : "").AppendLine(" }");
            }
        }
        output.AppendLine("return; }");
    }

    private static string Construct(AttributeData attribute, ISymbol owner, string? compareDisplay = null)
    {
        if (attribute.ConstructorArguments.Any(a => a.Kind == TypedConstantKind.Error)) throw Error(owner, "An attribute argument could not be resolved.");
        var args = compareDisplay ?? attribute.ConstructorArguments.Select(a => a.ToCSharpString()).ToCommaSeparatedString(includeSpace: true);
        var named = attribute.NamedArguments.Where(a => a.Key is not ("ErrorMessageResourceType" or "ErrorMessageResourceName"))
            .Select(a => "@" + a.Key + " = " + a.Value.ToCSharpString()).ToList();
        var resourceType = attribute.NamedArguments.FirstOrDefault(a => a.Key == "ErrorMessageResourceType").Value.Value as INamedTypeSymbol;
        var resourceName = attribute.NamedArguments.FirstOrDefault(a => a.Key == "ErrorMessageResourceName").Value.Value as string;
        if (resourceType is not null || resourceName is not null)
        {
            if (named.Any(n => n.StartsWith("@ErrorMessage =", StringComparison.Ordinal))) throw Error(owner, "Specify ErrorMessage or a resource, not both.");
            named.Add("ErrorMessage = " + Resource(resourceType, resourceName, owner));
        }
        var construction = "new " + attribute.AttributeClass!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "(" + args + ")";
        if (compareDisplay is not null) construction = "new global::Soenneker.Quark.Generated.ComparisonMessageAttribute(" + compareDisplay + ")";
        if ((attribute.AttributeClass.ToDisplayString() == Annotations + "RangeAttribute" || attribute.AttributeClass.ToDisplayString() == "Soenneker.Quark.QuarkRangeAttribute") && attribute.ConstructorArguments.Length == 3 && attribute.ConstructorArguments[0].Value is INamedTypeSymbol operand)
        {
            construction = "new global::Soenneker.Quark.Generated.TypedRangeAttribute<" + operand.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ">(" + Converter(operand, owner) + ", " + attribute.ConstructorArguments.Skip(1).Select(a => a.ToCSharpString()).ToCommaSeparatedString(includeSpace: true) + ")";
        }
        return construction +
            (named.Count == 0 ? "" : " { " + named.ToCommaSeparatedString(includeSpace: true) + " }");
    }

    private static string Converter(INamedTypeSymbol type, ISymbol owner)
    {
        var converter = type.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "System.ComponentModel.TypeConverterAttribute");
        if (converter?.ConstructorArguments.FirstOrDefault().Value is INamedTypeSymbol custom)
            return "new " + custom.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "()";
        if (type.TypeKind == TypeKind.Enum) return "new global::System.ComponentModel.EnumConverter(typeof(" + type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "))";
        if (type.ContainingNamespace.ToDisplayString() == "System" && type.Name is "Boolean" or "Byte" or "SByte" or "Int16" or "UInt16" or "Int32" or "UInt32" or "Int64" or "UInt64" or "Single" or "Double" or "Decimal" or "Char" or "String" or "DateTime" or "DateTimeOffset" or "TimeSpan" or "Guid" or "DateOnly" or "TimeOnly")
            return "new global::System.ComponentModel." + type.Name + "Converter()";
        throw Error(owner, "Typed Range requires a known converter or [TypeConverter(typeof(YourConverter))] on " + type.ToDisplayString());
    }

    private static string Display(IPropertySymbol property)
    {
        var attributes = Attributes(property).ToArray();
        var display = attributes.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == Annotations + "DisplayAttribute");
        if (display is not null)
        {
            var name = display.NamedArguments.FirstOrDefault(a => a.Key == "Name").Value.Value as string;
            var resource = display.NamedArguments.FirstOrDefault(a => a.Key == "ResourceType").Value.Value as INamedTypeSymbol;
            if (name is not null) return resource is null ? Literal(name) : Resource(resource, name, property);
        }
        // ValidationContext uses DisplayAttribute, not DisplayNameAttribute.
        return Literal(property.Name);
    }

    private static string Resource(INamedTypeSymbol? type, string? name, ISymbol owner)
    {
        var property = type?.GetMembers(name ?? "").OfType<IPropertySymbol>().FirstOrDefault(p => p.IsStatic && p.GetMethod?.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal && p.Type.SpecialType == SpecialType.System_String);
        if (property is null) throw Error(owner, "The validation resource must be an accessible static string property: " + name);
        return type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ".@" + name;
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);
    private static InvalidOperationException Error(ISymbol symbol, string message) => new("QV001: " + symbol.ToDisplayString() + ": " + message);
}
