using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using Soenneker.Utils.PooledStringBuilders;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Soenneker.Quark.Gen.Validation.BuildTasks;

/// <summary>Emits validation implementations for annotated models in a compilation.</summary>
public sealed class ValidationEmitter
{
    private const string _annotations = "System.ComponentModel.DataAnnotations.";

    private readonly Dictionary<IPropertySymbol, ImmutableArray<AttributeData>> _attributes = new(SymbolEqualityComparer.Default);
    private readonly Dictionary<INamedTypeSymbol, string> _names = new(SymbolEqualityComparer.Default);
    private readonly Dictionary<INamedTypeSymbol, bool> _validation = new(SymbolEqualityComparer.Default);
    private readonly Dictionary<INamedTypeSymbol, bool> _required = new(SymbolEqualityComparer.Default);
    private readonly Dictionary<ITypeSymbol, string> _qualifiedNames = new(SymbolEqualityComparer.Default);
    private readonly Dictionary<TypedConstant, string> _constants = new();
    private readonly Dictionary<string, string> _fields = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> _literals = new(StringComparer.Ordinal);
    private readonly Dictionary<IPropertySymbol, string> _display = new(SymbolEqualityComparer.Default);

    private ValidationEmitter() { }

    /// <summary>Generates deterministic C# validation source for the supplied compilation.</summary>
    public static string Emit(CSharpCompilation compilation, CancellationToken cancellationToken = default) =>
        new ValidationEmitter().EmitCore(compilation, cancellationToken);

    private string EmitCore(CSharpCompilation compilation, CancellationToken cancellationToken)
    {
        var output = new PooledStringBuilder(4096);
        var fields = new PooledStringBuilder(1024);
        try
        {
            output.Append("// <auto-generated/>\n#nullable enable\n");
            var seen = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
            var usesTypedRange = false;
            var usesComparison = false;
            foreach (SyntaxTree tree in compilation.SyntaxTrees.OrderBy(t => t.FilePath, StringComparer.Ordinal))
            {
                cancellationToken.ThrowIfCancellationRequested();
                SemanticModel? semantic = null;
                foreach (TypeDeclarationSyntax declaration in tree.GetRoot(cancellationToken).DescendantNodes(n => n is not (BaseMethodDeclarationSyntax or BasePropertyDeclarationSyntax or FieldDeclarationSyntax)).OfType<TypeDeclarationSyntax>())
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    if (!IsCandidate(declaration)) continue;
                    semantic ??= compilation.GetSemanticModel(tree);
                    if (semantic.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type || !seen.Add(type)) continue;
                    IPropertySymbol[] properties = Properties(type).ToArray();
                    if (!HasValidation(type, properties)) continue;
                    if (type.IsStatic || type.IsRefLikeType || type.IsFileLocal || type.TypeKind is not (TypeKind.Class or TypeKind.Struct))
                        throw Error(type, "Validation models must be ordinary classes, records, or structs.");
                    var chain = new Stack<INamedTypeSymbol>();
                    for (INamedTypeSymbol? current = type; current is not null; current = current.ContainingType)
                    {
                        if (current.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is not TypeDeclarationSyntax d || !d.Modifiers.Any(SyntaxKind.PartialKeyword)))
                            throw Error(current, "Add the partial modifier to this model and its containing types so generated code can access nested and generic models.");
                        chain.Push(current);
                    }
                    if (!type.ContainingNamespace.IsGlobalNamespace)
                    {
                        output.Append("namespace ");
                        output.Append(type.ContainingNamespace.ToDisplayString());
                        output.AppendLine(" {");
                    }
                    foreach (INamedTypeSymbol current in chain)
                    {
                        output.Append("partial ");
                        output.Append(current.IsRecord ? current.TypeKind == TypeKind.Struct ? "record struct " : "record class " : current.TypeKind == TypeKind.Struct ? "struct " : "class ");
                        output.Append('@');
                        output.Append(current.Name);

                        if (current.TypeParameters.Length > 0)
                        {
                            output.Append('<');
                            for (var parameterIndex = 0; parameterIndex < current.TypeParameters.Length; parameterIndex++)
                            {
                                if (parameterIndex != 0) output.Append(", ");
                                output.Append('@');
                                output.Append(current.TypeParameters[parameterIndex].Name);
                            }
                            output.Append('>');
                        }

                        if (SymbolEqualityComparer.Default.Equals(current, type)) output.Append(" : global::Soenneker.Quark.IGeneratedQuarkValidation");
                        output.AppendLine(" {");
                    }
                    output.AppendLine("void global::Soenneker.Quark.IGeneratedQuarkValidation.ValidateField(string memberName, global::System.Collections.Generic.ICollection<global::System.ComponentModel.DataAnnotations.ValidationResult> results) {");
                    output.AppendLine("switch (memberName) {");
                    fields.Clear();
                    _fields.Clear();
                    var fieldIndex = 0;
                    foreach (IPropertySymbol property in properties) EmitProperty(ref output, type, property, properties, ref fields, ref fieldIndex, ref usesTypedRange, ref usesComparison);
                    output.AppendLine("default: throw new global::System.ArgumentException(\"Unknown public validation property: \" + memberName, nameof(memberName));\n}\n}");
                    output.Append(fields.AsSpan());
                    foreach (INamedTypeSymbol _ in chain) output.AppendLine("}");
                    if (!type.ContainingNamespace.IsGlobalNamespace) output.AppendLine("}");
                }
            }
            if (usesTypedRange) output.AppendLine(TypedRangeSource.Text);
            if (usesComparison) output.AppendLine(ComparisonSource.Text);
            return output.ToString();
        }
        finally
        {
            fields.Dispose();
            output.Dispose();
        }
    }

    private static IEnumerable<IPropertySymbol> Properties(INamedTypeSymbol type)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);
        for (INamedTypeSymbol? current = type; current is not null; current = current.BaseType)
            foreach (ISymbol member in current.GetMembers())
                if (member is IPropertySymbol property && names.Add(property.Name) && !property.IsStatic && !property.IsIndexer && property.DeclaredAccessibility == Accessibility.Public &&
                    property.GetMethod?.DeclaredAccessibility == Accessibility.Public)
                    yield return property;
    }

    private bool HasValidation(INamedTypeSymbol type, IPropertySymbol[] properties)
    {
        foreach (AttributeData attribute in type.GetAttributes())
            if (attribute.AttributeClass is { Name: "GenerateQuarkValidationAttribute" } attributeType &&
                Name(attributeType) == "Soenneker.Quark.GenerateQuarkValidationAttribute")
                return true;

        foreach (IPropertySymbol property in properties)
            foreach (AttributeData attribute in Attributes(property))
                if (IsValidation(attribute))
                    return true;

        return false;
    }

    private ImmutableArray<AttributeData> Attributes(IPropertySymbol property)
    {
        // Roslyn already stores the direct attributes; most properties have no override
        // chain and need neither an iterator nor an inheritance deduplication set.
        if (property.OverriddenProperty is null) return property.GetAttributes();
        if (_attributes.TryGetValue(property, out ImmutableArray<AttributeData> result)) return result;
        result = InheritedAttributes(property).ToImmutableArray();
        _attributes.Add(property, result);
        return result;
    }

    private static IEnumerable<AttributeData> InheritedAttributes(IPropertySymbol property)
    {
        var attributes = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
        var inherited = false;
        for (IPropertySymbol? current = property; current is not null; current = current.OverriddenProperty)
        {
            foreach (AttributeData attribute in current.GetAttributes())
            {
                if (attribute.AttributeClass is null) continue;
                AttributeData? usage = attribute.AttributeClass.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "System.AttributeUsageAttribute");
                if (inherited && usage?.NamedArguments.Any(a => a.Key == "Inherited" && a.Value.Value is false) == true) continue;
                bool multiple = usage?.NamedArguments.Any(a => a.Key == "AllowMultiple" && a.Value.Value is true) == true;
                if (attributes.Add(attribute.AttributeClass) || multiple) yield return attribute;
            }
            inherited = true;
        }
    }

    private string Name(INamedTypeSymbol type)
    {
        if (!_names.TryGetValue(type, out string? name)) _names.Add(type, name = type.ToDisplayString());
        return name;
    }

    private bool IsValidation(AttributeData attribute)
    {
        if (attribute.AttributeClass is not { } type) return false;
        if (_validation.TryGetValue(type, out bool result)) return result;
        result = Name(type) is "Soenneker.Quark.QuarkCompareAttribute" or "Soenneker.Quark.QuarkRangeAttribute";
        for (INamedTypeSymbol? current = type; !result && current is not null; current = current.BaseType)
            result = current.Name == "ValidationAttribute" && Name(current) == _annotations + "ValidationAttribute";
        _validation.Add(type, result);
        return result;
    }

    private bool IsRequired(AttributeData attribute)
    {
        if (attribute.AttributeClass is not { } type) return false;
        if (_required.TryGetValue(type, out bool result)) return result;
        for (INamedTypeSymbol? current = type; current is not null; current = current.BaseType)
            if (current.Name == "RequiredAttribute" && Name(current) == _annotations + "RequiredAttribute") { result = true; break; }
        _required.Add(type, result);
        return result;
    }

    private void EmitProperty(ref PooledStringBuilder output, INamedTypeSymbol model, IPropertySymbol property, IPropertySymbol[] properties,
        ref PooledStringBuilder fields, ref int fieldIndex, ref bool usesTypedRange, ref bool usesComparison)
    {
        ImmutableArray<AttributeData> allAttributes = Attributes(property);
        List<AttributeData>? attributes = null;
        foreach (AttributeData attribute in allAttributes)
            if (IsValidation(attribute) && IsRequired(attribute)) (attributes ??= new List<AttributeData>(allAttributes.Length)).Add(attribute);
        foreach (AttributeData attribute in allAttributes)
            if (IsValidation(attribute) && !IsRequired(attribute)) (attributes ??= new List<AttributeData>(allAttributes.Length)).Add(attribute);
        output.Append("case ");
        output.Append(Literal(property.Name));
        output.AppendLine(": {");

        // Match TryValidateProperty: even a field without annotations reads its current getter.
        output.Append("var value = this.@");
        output.Append(property.Name);
        output.AppendLine(";");

        if (attributes is { Count: > 0 })
        {
            string display = Display(property);
            string displayExpression = display;
            if (display == "\"\"") displayExpression = "((object)this).GetType().Name";
            else if (!display.StartsWith('"'))
            {
                output.Append("var displayName = "); output.Append(display); output.Append(" ?? ");
                output.Append(Literal(property.Name)); output.AppendLine(";");
                output.AppendLine("if (global::System.String.IsNullOrEmpty(displayName)) displayName = ((object)this).GetType().Name;");
                displayExpression = "displayName";
            }
            bool needsContext = attributes.Any(a => !CanCache(a, Name(a.AttributeClass!)) && Name(a.AttributeClass!) is not (_annotations + "CompareAttribute" or "Soenneker.Quark.QuarkCompareAttribute"));
            if (needsContext) output.AppendLine("global::System.ComponentModel.DataAnnotations.ValidationContext? context = null;");
            string errorDisplay = needsContext ? "(context?.DisplayName ?? " + displayExpression + ")" : displayExpression;
            string? context = needsContext ? "(context ??= new global::System.ComponentModel.DataAnnotations.ValidationContext(this, " + displayExpression + ", null, null) { MemberName = " + Literal(property.Name) + " })" : null;
            for (var i = 0; i < attributes.Count; i++)
            {
                AttributeData attribute = attributes[i];
                string name = Name(attribute.AttributeClass!);
                string variable = "attribute" + i;
                string result = "result" + i;
                if (name == _annotations + "CompareAttribute" || name == "Soenneker.Quark.QuarkCompareAttribute")
                {
                    var otherName = attribute.ConstructorArguments[0].Value as string;
                    IPropertySymbol? other = properties.FirstOrDefault(p => p.Name == otherName);
                    if (other is null) throw Error(property, "Compare references an unknown public readable property: " + otherName);
                    usesComparison = true;
                    if (SymbolEqualityComparer.Default.Equals(property.Type, other.Type) && ValidationFastPath.CanCompareWithoutBoxing(property.Type))
                    {
                        output.Append("if (!global::System.Collections.Generic.EqualityComparer<");
                        output.Append(Qualified(property.Type));
                        output.Append(">.Default.Equals(value, this.@");
                    }
                    else output.Append("if (!global::System.Object.Equals(value, this.@");
                    output.Append(other.Name);
                    output.AppendLine("))");

                    output.AppendLine("{");
                    output.Append("var ");
                    output.Append(variable);
                    output.Append(" = ");
                    output.Append(Construct(attribute, property, Display(other)));
                    output.AppendLine(";");

                    output.Append("results.Add(new global::System.ComponentModel.DataAnnotations.ValidationResult(");
                    output.Append(variable);
                    output.Append(".FormatErrorMessage(");
                    output.Append(errorDisplay);
                    output.Append("), new[] { memberName }));");
                    output.AppendLine();

                    output.AppendLine("}");
                    continue;
                }
                string construction = Construct(attribute, property);
                bool typedRange = construction.StartsWith("new global::Soenneker.Quark.Generated.TypedRangeAttribute<", StringComparison.Ordinal);
                usesTypedRange |= typedRange;
                // Only share known context-free framework validators. Custom attributes and
                // resource expressions retain per-call instances; range caches respect culture.
                bool cached = CanCache(attribute, name);
                string? fastPath = cached ? ValidationFastPath.Get(attribute, name, property.Type) : null;
                if (fastPath == "true") continue;
                if (fastPath is not null)
                {
                    output.Append("if (!("); output.Append(fastPath); output.AppendLine(")) {");
                }
                if (cached)
                {
                    bool newField = !_fields.TryGetValue(construction, out string? field);
                    if (newField)
                    {
                        do { field = "__quarkValidationAttribute" + fieldIndex++; } while (IsReserved(model, properties, field));
                        _fields.Add(construction, field);
                    }
                    string attributeType = typedRange
                        ? "global::Soenneker.Quark.Generated.TypedRangeAttribute<" + Qualified((INamedTypeSymbol)attribute.ConstructorArguments[0].Value!) + ">"
                        : Qualified(attribute.AttributeClass!);
                    string factory = name is _annotations + "RangeAttribute" or "Soenneker.Quark.QuarkRangeAttribute"
                        ? "{ var attribute = " + construction + "; attribute.IsValid(null); return attribute; }" : construction;
                    bool invariantLimits = typedRange && attribute.NamedArguments.Any(a => a.Key == "ParseLimitsInInvariantCulture" && a.Value.Value is true);
                    if (name == _annotations + "RegularExpressionAttribute" || (typedRange && !invariantLimits))
                    {
                        // Inline case-insensitive regex options capture the current culture.
                        if (newField)
                        {
                            fields.Append("private static readonly global::System.Runtime.CompilerServices.ConditionalWeakTable<global::System.Globalization.CultureInfo, ");
                            fields.Append(attributeType);
                            fields.Append("> ");
                            fields.Append(field);
                            fields.AppendLine(" = new();");

                        }
                        output.Append("var culture"); output.Append(i); output.Append(" = global::System.Globalization.CultureInfo.");
                        output.AppendLine("CurrentCulture;");
                        output.Append("var "); output.Append(variable); output.Append(" = culture"); output.Append(i);
                        output.Append(".IsReadOnly ? "); output.Append(field); output.Append(".GetValue(culture"); output.Append(i);
                        output.Append(", static _ => "); output.Append(factory); output.Append(") : "); output.Append(construction); output.AppendLine(";");
                        if (typedRange)
                        {
                            // Invalid limits must still throw for null values when mutable cultures bypass the cache.
                            output.Append("if (!culture"); output.Append(i); output.Append(".IsReadOnly) ");
                            output.Append(variable); output.AppendLine(".IsValid(null);");
                        }

                    }
                    else
                    {
                        if (newField)
                        {
                            fields.Append("private static ");
                            fields.Append(attributeType);
                            fields.Append("? ");
                            fields.Append(field);
                            fields.AppendLine(";");

                        }
                        output.Append("var ");
                        output.Append(variable);
                        output.Append(" = global::System.Threading.LazyInitializer.EnsureInitialized(ref ");
                        output.Append(field);
                        output.Append(", static () => ");
                        output.Append(factory);
                        output.AppendLine(");");

                    }
                    if (fastPath is null)
                    {
                        var nullableType = property.Type as INamedTypeSymbol;
                        bool nullable = nullableType?.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
                        ITypeSymbol valueType = nullable ? nullableType!.TypeArguments[0] : property.Type;
                        output.Append("if (!(");
                        if (typedRange && SymbolEqualityComparer.Default.Equals(valueType, attribute.ConstructorArguments[0].Value as ITypeSymbol))
                        {
                            if (nullable) output.Append("!value.HasValue || ");
                            else if (valueType.SpecialType == SpecialType.System_String) output.Append("global::System.String.IsNullOrEmpty(value) || ");
                            output.Append(variable);
                            output.Append(nullable ? ".IsValidTyped(value.GetValueOrDefault())" : ".IsValidTyped(value)");
                        }
                        else { output.Append(variable); output.Append(".IsValid(value)"); }
                        output.AppendLine(")) {");
                    }

                }
                else
                {
                    output.Append("var ");
                    output.Append(variable);
                    output.Append(" = ");
                    output.Append(construction);
                    output.AppendLine(";");
                }
                if (cached)
                {
                    output.Append("results.Add(new global::System.ComponentModel.DataAnnotations.ValidationResult(");
                    output.Append(variable); output.Append(".FormatErrorMessage("); output.Append(errorDisplay);
                    output.Append("), ");
                    output.Append(needsContext ? "context is null ? new[] { memberName } : context.MemberName is null ? global::System.Array.Empty<string>() : new[] { context.MemberName }" : "new[] { memberName }");
                    output.AppendLine("));");
                    if (IsRequired(attribute)) output.AppendLine("return;");
                }
                else
                {
                    output.Append("var "); output.Append(result); output.Append(" = "); output.Append(variable);
                    output.Append(".GetValidationResult(value, "); output.Append(context); output.AppendLine(");");
                    output.Append("if ("); output.Append(result); output.Append(" is not null) { results.Add("); output.Append(result);
                    output.Append(");"); output.Append(IsRequired(attribute) ? " return;" : ""); output.AppendLine(" }");
                }

                if (cached) output.AppendLine("}");
            }
        }
        output.AppendLine("return; }");
    }

    private static bool IsReserved(INamedTypeSymbol model, IPropertySymbol[] properties, string name)
    {
        if (model.Name == name || model.GetMembers(name).Length != 0) return true;
        foreach (IPropertySymbol property in properties)
            if (property.Name == name) return true;
        foreach (ITypeParameterSymbol parameter in model.TypeParameters)
            if (parameter.Name == name) return true;
        return false;
    }

    private static bool CanCache(AttributeData attribute, string name)
    {
        if (attribute.NamedArguments.Any(a => a.Key is "ErrorMessageResourceType" or "ErrorMessageResourceName")) return false;
        if (name is _annotations + "RequiredAttribute" or _annotations + "StringLengthAttribute" or
            _annotations + "MinLengthAttribute" or _annotations + "MaxLengthAttribute" or
            _annotations + "LengthAttribute" or _annotations + "EmailAddressAttribute" or
            _annotations + "PhoneAttribute" or _annotations + "UrlAttribute" or
            _annotations + "CreditCardAttribute" or _annotations + "RegularExpressionAttribute" or
            _annotations + "Base64StringAttribute" or _annotations + "FileExtensionsAttribute" or
            _annotations + "EnumDataTypeAttribute" or _annotations + "AllowedValuesAttribute" or _annotations + "DeniedValuesAttribute") return true;
        if (name is not (_annotations + "RangeAttribute" or "Soenneker.Quark.QuarkRangeAttribute")) return false;
        if (attribute.ConstructorArguments.Length == 2) return true;
        if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol operand || operand.ContainingNamespace.ToDisplayString() != "System") return false;
        return operand.Name is "Boolean" or "Byte" or "SByte" or "Int16" or "UInt16" or "Int32" or "UInt32" or "Int64" or "UInt64" or
            "Single" or "Double" or "Decimal" or "Char" or "String" or "DateTime" or "DateTimeOffset" or "TimeSpan" or "Guid" or "DateOnly" or "TimeOnly";
    }

    private string Qualified(ITypeSymbol type)
    {
        if (!_qualifiedNames.TryGetValue(type, out string? name)) _qualifiedNames.Add(type, name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        return name;
    }

    private string Constant(TypedConstant constant)
    {
        if (_constants.TryGetValue(constant, out string? value)) return value;
        if (constant.IsNull)
        {
            value = constant.Type is null ? "null" : "(" + Qualified(constant.Type) + ")null";
            _constants.Add(constant, value);
            return value;
        }
        if (constant.Kind == TypedConstantKind.Array)
        {
            var builder = new PooledStringBuilder(128);
            try
            {
                builder.Append("new "); builder.Append(Qualified(constant.Type!)); builder.Append(" { ");
                for (var i = 0; i < constant.Values.Length; i++)
                {
                    if (i != 0) builder.Append(", ");
                    builder.Append(Constant(constant.Values[i]));
                }
                builder.Append(" }");
                value = builder.ToString();
            }
            finally { builder.Dispose(); }
            _constants.Add(constant, value);
            return value;
        }
        // Preserve overload selection and emit valid C# for non-finite floating-point constants.
        value = constant.Value switch
        {
            double number => double.IsNaN(number) ? "global::System.Double.NaN" :
                double.IsPositiveInfinity(number) ? "global::System.Double.PositiveInfinity" :
                double.IsNegativeInfinity(number) ? "global::System.Double.NegativeInfinity" : number.ToString("R", CultureInfo.InvariantCulture) + "D",
            float number => float.IsNaN(number) ? "global::System.Single.NaN" :
                float.IsPositiveInfinity(number) ? "global::System.Single.PositiveInfinity" :
                float.IsNegativeInfinity(number) ? "global::System.Single.NegativeInfinity" : number.ToString("R", CultureInfo.InvariantCulture) + "F",
            _ => constant.ToCSharpString()
        };
        _constants.Add(constant, value);
        return value;
    }

    private string Construct(AttributeData attribute, ISymbol owner, string? compareDisplay = null)
    {
        foreach (TypedConstant argument in attribute.ConstructorArguments)
            if (argument.Kind == TypedConstantKind.Error) throw Error(owner, "An attribute argument could not be resolved.");
        INamedTypeSymbol? resourceType = null;
        string? resourceName = null;
        var errorMessage = false;
        foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
        {
            if (argument.Key == "ErrorMessageResourceType") resourceType = argument.Value.Value as INamedTypeSymbol;
            else if (argument.Key == "ErrorMessageResourceName") resourceName = argument.Value.Value as string;
            else if (argument.Key == "ErrorMessage") errorMessage = true;
        }
        bool hasResource = resourceType is not null || resourceName is not null;
        if (hasResource && errorMessage) throw Error(owner, "Specify ErrorMessage or a resource, not both.");
        var builder = new PooledStringBuilder(256);
        try
        {
            builder.Append("new ");
            string name = Name(attribute.AttributeClass!);
            if (compareDisplay is not null)
            {
                builder.Append("global::Soenneker.Quark.Generated.ComparisonMessageAttribute(");
                builder.Append(compareDisplay);
            }
            else if (name is _annotations + "RangeAttribute" or "Soenneker.Quark.QuarkRangeAttribute" &&
                     attribute.ConstructorArguments.Length == 3 && attribute.ConstructorArguments[0].Value is INamedTypeSymbol operand)
            {
                builder.Append("global::Soenneker.Quark.Generated.TypedRangeAttribute<");
                builder.Append(Qualified(operand));
                builder.Append(">("); builder.Append(Converter(operand, owner)); builder.Append(", ");
                builder.Append(Constant(attribute.ConstructorArguments[1])); builder.Append(", ");
                builder.Append(Constant(attribute.ConstructorArguments[2]));
            }
            else
            {
                builder.Append(Qualified(attribute.AttributeClass!)); builder.Append('(');
                for (var i = 0; i < attribute.ConstructorArguments.Length; i++)
                {
                    if (i != 0) builder.Append(", ");
                    builder.Append(Constant(attribute.ConstructorArguments[i]));
                }
            }
            builder.Append(')');
            var hasNamed = false;
            foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
            {
                if (argument.Key is "ErrorMessageResourceType" or "ErrorMessageResourceName") continue;
                builder.Append(hasNamed ? ", @" : " { @");
                hasNamed = true;
                builder.Append(argument.Key); builder.Append(" = "); builder.Append(Constant(argument.Value));
            }
            if (hasResource)
            {
                builder.Append(hasNamed ? ", ErrorMessage = " : " { ErrorMessage = ");
                builder.Append(Resource(resourceType, resourceName, owner));
                hasNamed = true;
            }
            if (hasNamed) builder.Append(" }");
            return builder.ToString();
        }
        finally { builder.Dispose(); }
    }

    private static string Converter(INamedTypeSymbol type, ISymbol owner)
    {
        AttributeData? converter = type.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "System.ComponentModel.TypeConverterAttribute");
        if (converter?.ConstructorArguments.FirstOrDefault().Value is INamedTypeSymbol custom)
            return "new " + custom.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "()";
        if (type.TypeKind == TypeKind.Enum) return "new global::System.ComponentModel.EnumConverter(typeof(" + type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "))";
        if (type.ContainingNamespace.ToDisplayString() == "System" && type.Name is "Boolean" or "Byte" or "SByte" or "Int16" or "UInt16" or "Int32" or "UInt32" or "Int64" or "UInt64" or "Single" or "Double" or "Decimal" or "Char" or "String" or "DateTime" or "DateTimeOffset" or "TimeSpan" or "Guid" or "DateOnly" or "TimeOnly")
            return "new global::System.ComponentModel." + type.Name + "Converter()";
        throw Error(owner, "Typed Range requires a known converter or [TypeConverter(typeof(YourConverter))] on " + type.ToDisplayString());
    }

    private string Display(IPropertySymbol property)
    {
        if (_display.TryGetValue(property, out string? expression)) return expression;
        ImmutableArray<AttributeData> attributes = Attributes(property);
        AttributeData? display = attributes.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == _annotations + "DisplayAttribute");
        if (display is not null)
        {
            var name = display.NamedArguments.FirstOrDefault(a => a.Key == "Name").Value.Value as string;
            var resource = display.NamedArguments.FirstOrDefault(a => a.Key == "ResourceType").Value.Value as INamedTypeSymbol;
            if (name is not null)
            {
                expression = resource is null ? Literal(name) : Resource(resource, name, property);
                _display.Add(property, expression);
                return expression;
            }
        }
        // ValidationContext uses DisplayAttribute, not DisplayNameAttribute.
        expression = Literal(property.Name);
        _display.Add(property, expression);
        return expression;
    }

    private static string Resource(INamedTypeSymbol? type, string? name, ISymbol owner)
    {
        IPropertySymbol? property = type?.GetMembers(name ?? "").OfType<IPropertySymbol>().FirstOrDefault(p => p.IsStatic && p.GetMethod?.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal && p.Type.SpecialType == SpecialType.System_String);
        if (property is null) throw Error(owner, "The validation resource must be an accessible static string property: " + name);
        return type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ".@" + name;
    }

    private string Literal(string value)
    {
        if (!_literals.TryGetValue(value, out string? literal)) _literals.Add(value, literal = SymbolDisplay.FormatLiteral(value, true));
        return literal;
    }

    private static bool IsCandidate(TypeDeclarationSyntax declaration)
    {
        if (declaration.AttributeLists.Count != 0 || declaration.BaseList is not null) return true;
        foreach (MemberDeclarationSyntax member in declaration.Members)
            if (member is PropertyDeclarationSyntax { AttributeLists.Count: > 0 }) return true;
        if (declaration is RecordDeclarationSyntax { ParameterList: { } parameters })
            foreach (ParameterSyntax parameter in parameters.Parameters)
                if (parameter.AttributeLists.Count != 0) return true;
        return false;
    }
    private static InvalidOperationException Error(ISymbol symbol, string message) => new("QV001: " + symbol.ToDisplayString() + ": " + message);
}
